x-app-base: &app-base
  image: "${DOCKER_IMAGE_BACKEND}:${TAG-latest}"
  env_file:
    - .env.local
  networks:
    - app-network
  restart: unless-stopped
  environment: &common-env
    POSTGRES_SERVER: db
    POSTGRES_PORT: ${POSTGRES_PORT}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/${RABBITMQ_VHOST}

services:
  db:
    image: postgres:17
    container_name: ${DB_CONTAINER}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.local
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network

  backend:
    <<: *app-base
    build:
      context: ./backend
    container_name: ${BACKEND_CONTAINER}
    restart: on-failure
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    environment:
      <<: *common-env
      DOMAIN: ${DOMAIN}
      FRONTEND_HOST: ${FRONTEND_HOST}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}

  rabbitmq:
    image: rabbitmq:4.2
    container_name: ${RABBIT_CONTAINER}
    env_file:
      - .env.local
    hostname: "rabbitmq"
    ports:
      - '${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}'
      - '${RABBITMQ_MGMT_PORT}:${RABBITMQ_MGMT_PORT}'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    networks:
      - app-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
  celery:
    <<: *app-base
    entrypoint: []
    command: celery -A data.tasks worker -l info
    container_name: ${CELERY_CONTAINER}
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      backend:
        condition: service_started
    restart: unless-stopped

  celery-beat:
    <<: *app-base
    entrypoint: []
    command: celery -A data.tasks beat -l info
    container_name: ${CELERY_BEAT_CONTAINER}
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      backend:
        condition: service_started

  nginx:
    image: "${DOCKER_IMAGE_FRONTEND}:${TAG-latest}"
    container_name: ${NGINX_CONTAINER}
    env_file:
      - .env.local
    build:
      context: ./frontend
      target: production 
    restart: always
    depends_on:
      - backend
      - db
    networks:
      - app-network

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: ${NPM_CONTAINER}
    env_file:
      - .env.local
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${NPM_HTTP_PORT}:${NPM_HTTP_PORT}'
      - '${NPM_ADMIN_PORT}:${NPM_ADMIN_PORT}'
      - '${NPM_HTTPS_PORT}:${NPM_HTTPS_PORT}'
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - app-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: ${PROMETHEUS_CONTAINER}
    env_file:
      - .env.local
    ports:
      - '${PROMETHEUS_PORT}:${PROMETHEUS_PORT}'
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${NODE_EXPORTER_CONTAINER}
    env_file:
      - .env.local
    ports:
      - '${NODE_EXPORTER_PORT}:${NODE_EXPORTER_PORT}'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: ${GRAFANA_CONTAINER}
    restart: unless-stopped
    ports:
      - '${GRAFANA_PORT}:${GRAFANA_PORT}'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/monitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    env_file:
      - .env.local
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER}
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  app-network:
    driver: bridge
    
volumes:
  app-db-data:
  rabbitmq-data:
  frontend-dist:
  prometheus-data:
  grafana-storage:
  redis-data: