$ANSIBLE_VAULT;1.1;AES256
38616132373665386361336337643161653266336163353062356231346362633430633730346563
6630373932303161396338366439343036633464633532350a666232636364373966383066363063
34363666623639643166626665666232623536323338666537316132323562646534346361336664
3463623138386335320a323833373035366466363034633838633131656435316238633963316261
39343562653263336530353834333734393963633263636239313032323032613330356138303336
63616261383266666465363537373763373666393234663565613263333564653565396537643837
30333232303530666363306566313137323936363838313334353864646136353232303538333066
66363534336434313636643336313163376637646161663039646133313730313231653262383232
61386338613032316263626364643162663363636339613030376138306562643533
