container_command:
container_env: {}
container_host_group:
container_ports: []
container_volumes: []
container_workdir:

container_images:
  - name: "postgres:17"
  - name: "rabbitmq:4.2"
  - name: "jasmar2/react-app:{{ app_tag | default('latest') }}"
  - name: "jasmar2/fastapi-app:{{ app_tag | default('latest') }}"
  - name: "jc21/nginx-proxy-manager:latest"