- name: UFW 
  hosts: webservers
  tasks:
    - name: UFW config
      include_role:
        name: ufw
- name: Docker
  hosts: webservers
  tasks:
    - name: Configure Docker
      include_role:
        name: docker
    - name: Pull containers
      include_role:
        name: container